### ISSUE TITLE
Rails 6

### ISSUE THREAD

**Issue by mkamensky** [take-five/activerecord-hierarchical_query#27]
Is there an issue supporting it? Thanks

**Comment by zachaysan** [comment]
There are some failing tests, yeah. From my vantage point it looks like ActiveRecord has some poorly generated SQL after the latest refactor, so I'm inclined to wait it out and hope it fixes itself. But if you'd like to try your own hand at it, it's a pretty easy repo to get the tests running in, though you do need `sudo` in order to create the test db.

**Comment by zachaysan** [comment]
@mkamensky I think I have a fix ready here. I'm going cut a gem. Let me know if there are problems in your test suite.

**Comment by zachaysan** [comment]
Ok latest Gem has a fix for Rails 6 support, let me know if there are any other issues.

**Comment by mkamensky** [comment]
Thank you!

**Comment by mkamensky** [comment]
Now 6.0.1 is here...

**Comment by zachaysan** [comment]
What's the issue @mkamensky ?

**Comment by anfinil** [comment]
@zachaysan @mkamensky 6.0.1  returns ```undefined method `join_recursive' for class```

**Comment by anfinil** [comment]
https://github.com/take-five/activerecord-hierarchical_query/pull/28 fixes it

**Comment by mkamensky** [comment]
Thanks, for the issue was simply that rails 6.0.1 is incompatible with the latest version, bundle was pulling an old one.

**Comment by zachaysan** [comment]
Ah, gotcha. Thanks for the PR @anfinil I've cut the new gem let me know if there are any problems.
