### ISSUE TITLE
Rails 7?

### ISSUE THREAD

**Issue by rctneil** [take-five/activerecord-hierarchical_query#34]
Hi,

Is rails 7 support coming?

**Comment by zachaysan** [comment]
Hey sorry about this, I'm swamped with work.

@artplan1 opened a PR for this earlier today. 

https://github.com/take-five/activerecord-hierarchical_query/pull/35

Since I'm not using rails 7 at the moment I'm unable to test it, but I've published a version `1.4.0.alpha1` that contains rails 7 support. Can you please verify for me that it works for you so I can move it out of alpha? 

Thanks in advance!

**Comment by evazion** [comment]
I've been using it in production for a week with no issues. The test suite also passes under Rails 7.

**Comment by zachaysan** [comment]
Ok great evazion. I've released a new gem out of alpha. Should be installable for `1.4.0`. Thank you very much for letting me know.

**Comment by zachaysan** [comment]
Official support for Rails 7 is now here. Please open a new issue if there are any problems. I'm on a python project at the moment so I'm not current on the latest changes in Rails, but I'll do my best to keep this working.
